FROM NODE:14

ARG API_URL

RUN mkdir -p /app
COPY ./packages/frontend /app

WORKDIR /app

RUN yarn install --production=false
RUN yarn build

ENV API_URL ${API_URL}
ENV PORT 3000
ENV HOST 0.0.0.0

CMD ["node", "build/index.js"]