FROM NODE:14

ARG DATABASE_PROVIDER
ARG DATABASE_URL

RUN mkdir -p /app
COPY ./packages/api /app

WORKDIR /app

RUN yarn install --production=false
RUN yarn build

VOLUME /app/public/images

ENV DATABASE_PROVIDER ${DATABASE_PROVIDER}
ENV DATABASE_URL ${DATABASE_URL}
ENV PORT 3000
ENV HOST 0.0.0.0

CMD ["yarn", "start"]